apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-updates-test
  labels:
    app: rolling-updates-test
    variant: jvm
  namespace: default
spec:
  replicas: 6
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: rolling-updates-test
      version: stable
      variant: jvm
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /q/metrics
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
      labels:
        app: rolling-updates-test
        version: stable
        variant: jvm
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: local/rolling-updates-test:latest
        imagePullPolicy: Never
        startupProbe:
          failureThreshold: 30
          periodSeconds: 10
          httpGet:
            path: /q/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /q/health
            port: 8080
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /q/health
            port: 8080
        name: rolling-updates-test
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi
