kind: Service
apiVersion: v1
metadata:
  name: rolling-updates-test
  namespace: default
spec:
  selector:
    app: rolling-updates-test
    variant: jvm
    version: stable
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: http
